import sys
import logging
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent))

from fastapi import APIRouter, Depends, HTTPException, Query
from typing import Optional

from models.schemas import (
    GeospatialResponse, GeospatialPoint,
    HotspotSummary, HotspotDetailResponse, JointPatrolRecommendation,
)
from utils.auth import require_officer
from utils.geo_query_engine import (
    load_data,
    get_top_hotspots,
    get_hotspot_detail,
    get_joint_patrol_recommendations,
    simulate_near_real_time_update,
)
import json, os

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/geospatial", tags=["Geospatial"])

DATA_FILE = "../data/geospatial_data.json"


def load_geo_data():
    """Load the real dataset generated by TM3's synthetic data script.
    Used only by the legacy /  endpoint below for raw point filtering."""
    if not os.path.exists(DATA_FILE):
        logger.error(f"[geospatial] {DATA_FILE} not found")
        raise HTTPException(status_code=503,
                             detail=f"Geospatial data file not found at {DATA_FILE}")
    with open(DATA_FILE) as f:
        return json.load(f)


def _safe_load_engine_data():
    """Wraps geo_query_engine.load_data() so a missing sklearn install or
    missing JSON degrades gracefully instead of 500-ing the whole router,
    mirroring how scam_engine._get_omniroute_client() degrades on a missing key."""
    try:
        return load_data()
    except Exception as e:
        logger.warning(f"[geospatial] engine load_data() failed, hotspot endpoints "
                        f"will return empty results: {e}")
        import pandas as pd
        empty = pd.DataFrame()
        return empty, empty, empty


@router.get("/", response_model=GeospatialResponse, dependencies=[Depends(require_officer)])
def get_heatmap(
    state: Optional[str] = Query(None, description="Filter by state name"),
    crime_type: Optional[str] = Query(None, description="Filter by crime type")
):
    """Legacy raw-point heatmap endpoint (unchanged)."""
    raw = load_geo_data()

    if state:
        raw = [p for p in raw if p["state"].lower() == state.lower()]
    if crime_type:
        raw = [p for p in raw if p["crime_type"] == crime_type]

    points = [GeospatialPoint(**p) for p in raw]
    hotspots = list({p.state for p in sorted(points, key=lambda x: -x.complaint_count)[:5]})

    return GeospatialResponse(
        points=points,
        total_complaints=sum(p.complaint_count for p in points),
        hotspot_states=hotspots
    )


@router.get("/hotspots", response_model=list[HotspotSummary],
            dependencies=[Depends(require_officer)])
def hotspots(n: int = Query(10, ge=1, le=100, description="Number of top hotspots to return")):
    """Ranked patrol-priority hotspot list for the command-centre map panel."""
    hotspots_df, _, _ = _safe_load_engine_data()
    if hotspots_df.empty:
        return []
    return get_top_hotspots(hotspots_df, n).to_dict(orient="records")


@router.get("/hotspots/{cluster_id}", response_model=HotspotDetailResponse,
            dependencies=[Depends(require_officer)])
def hotspot_detail(cluster_id: str):
    """Drill-down: all events inside one hotspot cluster."""
    hotspots_df, events_df, _ = _safe_load_engine_data()
    if hotspots_df.empty:
        raise HTTPException(status_code=503, detail="Geospatial engine data unavailable")

    summary, detail = get_hotspot_detail(hotspots_df, events_df, cluster_id)
    if summary.empty:
        raise HTTPException(status_code=404, detail=f"No hotspot found for cluster_id={cluster_id}")

    return HotspotDetailResponse(
        summary=summary.to_dict(orient="records"),
        events=detail.to_dict(orient="records"),
    )


@router.get("/joint-patrols", response_model=list[JointPatrolRecommendation],
            dependencies=[Depends(require_officer)])
def joint_patrols(top_n: int = Query(5, ge=1, le=50)):
    """Cross-district/state coordination candidates for inter-district
    intelligence sharing."""
    _, _, joint_ops_df = _safe_load_engine_data()
    if joint_ops_df.empty:
        return []
    return get_joint_patrol_recommendations(joint_ops_df, top_n).to_dict(orient="records")